name: CICD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nexus:
        image: sonatype/nexus3:latest
        ports:
          - 8081:8081
          - 8082:8082
        options: >-
          --health-cmd "curl -f http://localhost:8081 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4

      - name: set up java 
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven Wrapper
        run: ./mvnw -B verify -Dtest=!PostgresIntegrationTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: |
            spring-petclinic:latest
            localhost:8081/spring-petclinic/spring-petclinic:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'spring-petclinic:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Push image to Nexus
        run: docker push localhost:8081/spring-petclinic/spring-petclinic:latest